name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: docker compose down
      run: docker compose down    
    - name: Remove the Docker image
      run: docker image rm nlabosesamebot-app:latest
    - name: Build the Docker image
      run: docker compose up -d

    
