name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: docker compose down
      run: docker compose down 
      continue-on-error: true
    - name: Remove the Docker image
      run: docker image rm nlabosesamebot-app:latest
      continue-on-error: true
    - name: Build the Docker image
      run: docker compose up -e PUBLIC_KEY -e SECRET_KEY -e BLE_MAC -e BLE_UUID -e DISCORD_CHANNEL -e DISCORD_GUILD -e DISCORD_TOKEN -d

    
